<?php

namespace Database\Seeders\ClothesShop;

use Illuminate\Database\Seeder;
use App\Models\Finance\PostingScenario;
use Illuminate\Support\Facades\DB;

class PostingScenarioSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        PostingScenario::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $scenarios = [

            // ============================================================
            // المشتريات - الاحتفاظ بالسيناريوهات الحالية
            // ============================================================
            [
                'code' => 'PURCHASE_CASH',
                'name' => 'شراء نقدي',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات مدفوعة كاش',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_CREDIT',
                'name' => 'شراء آجل',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات آجلة (على ذمة المورد)',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_INSTALLMENTS',
                'name' => 'شراء بالتقسيط',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات بالتقسيط',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_WALLET',
                'name' => 'شراء بالمحفظة الإلكترونية',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات مدفوعة من المحفظة الإلكترونية',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_BANK_ONLINE',
                'name' => 'شراء عن طريق البنك أونلاين',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات مدفوعة عن طريق البنك أونلاين',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_BANK_DIRECT',
                'name' => 'شراء عن طريق البنك مباشر',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات مدفوعة عن طريق البنك مباشرة',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_CHECK',
                'name' => 'شراء بشيك',
                'operation_type' => 'purchase',
                'priority' => 10,
                'description' => 'فاتورة مشتريات مدفوعة بشيك',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_CASH',
                'name' => 'مرتجع مشتريات نقدي',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع منتج لمورد مع استرداد نقدي',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_CREDIT',
                'name' => 'مرتجع مشتريات آجل',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع منتج لمورد مع تخفيض رصيده',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_INSTALLMENTS',
                'name' => 'مرتجع مشتريات بالتقسيط',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع منتج لمورد مع تخفيض رصيد الأقساط',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_WALLET',
                'name' => 'مرتجع مشتريات بالمحفظة الإلكترونية',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع مبلغ المرتجع إلى المحفظة الإلكترونية',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_BANK_ONLINE',
                'name' => 'مرتجع مشتريات البنك أونلاين',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع مبلغ المرتجع عبر البنك أونلاين',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_BANK_DIRECT',
                'name' => 'مرتجع مشتريات البنك مباشر',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'استرجاع مبلغ المرتجع عبر البنك مباشرة',
                'is_active' => 1,
            ],
            [
                'code' => 'PURCHASE_RETURN_CHECK',
                'name' => 'مرتجع مشتريات بشيك',
                'operation_type' => 'purchase_return',
                'priority' => 10,
                'description' => 'تسوية مرتجع مشتريات مرتبط بشيك',
                'is_active' => 1,
            ],

            // ============================================================
            // طلبات المتجر الإلكتروني (Order)
            // لدعم الكوبون والعرض ومصاريف الشحن كبنود مستقلة
            // ============================================================
            [
                'code' => 'ORDER_CASH',
                'name' => 'طلب نقدي',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر مدفوع نقداً',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_CREDIT',
                'name' => 'طلب آجل',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر آجل على ذمة العميل',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_INSTALLMENTS',
                'name' => 'طلب بالتقسيط',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر بالتقسيط',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_WALLET',
                'name' => 'طلب بالمحفظة الإلكترونية',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر مدفوع من المحفظة الإلكترونية',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_BANK_ONLINE',
                'name' => 'طلب عن طريق البنك أونلاين',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر مدفوع عن طريق البنك أونلاين',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_BANK_DIRECT',
                'name' => 'طلب عن طريق البنك مباشر',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر مدفوع عن طريق البنك مباشرة',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_CHECK',
                'name' => 'طلب بشيك',
                'operation_type' => 'order',
                'priority' => 10,
                'description' => 'طلب متجر مدفوع بشيك',
                'is_active' => 1,
            ],

            // مرتجعات طلبات المتجر الإلكتروني
            [
                'code' => 'ORDER_RETURN_CASH',
                'name' => 'مرتجع طلب نقدي',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر مع رد المبلغ نقداً',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_CREDIT',
                'name' => 'مرتجع طلب آجل',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر مع تخفيض رصيد العميل',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_INSTALLMENTS',
                'name' => 'مرتجع طلب بالتقسيط',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر مع تخفيض رصيد الأقساط',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_WALLET',
                'name' => 'مرتجع طلب بالمحفظة الإلكترونية',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر ورد المبلغ إلى المحفظة الإلكترونية',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_BANK_ONLINE',
                'name' => 'مرتجع طلب البنك أونلاين',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر ورد المبلغ عبر البنك أونلاين',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_BANK_DIRECT',
                'name' => 'مرتجع طلب البنك مباشر',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'مرتجع طلب متجر ورد المبلغ عبر البنك مباشرة',
                'is_active' => 1,
            ],
            [
                'code' => 'ORDER_RETURN_CHECK',
                'name' => 'مرتجع طلب بشيك',
                'operation_type' => 'sales_return',
                'priority' => 10,
                'description' => 'تسوية مرتجع طلب متجر مرتبط بشيك',
                'is_active' => 1,
            ],

            // ============================================================
            // السندات - الأكواد يجب أن تطابق ScenarioResolver حرفياً
            // VOUCHER_{RECEIPT|PAYMENT}_{PAYMENT_TYPE}_{PARTY_TYPE}
            // ============================================================
            [
                'code'           => 'VOUCHER_RECEIPT_CASH_CUSTOMER',
                'name'           => 'سند قبض نقدي - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة نقدي للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CASH_SUPPLIER',
                'name'           => 'سند قبض نقدي - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة نقدي للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CASH_OTHER',
                'name'           => 'سند قبض نقدي - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة نقدي للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CREDIT_CUSTOMER',
                'name'           => 'سند قبض بنكي - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنكي للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CREDIT_SUPPLIER',
                'name'           => 'سند قبض بنكي - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنكي للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CREDIT_OTHER',
                'name'           => 'سند قبض بنكي - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنكي للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_INSTALLMENTS_CUSTOMER',
                'name'           => 'سند قبض تقسيط - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة تقسيط للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_INSTALLMENTS_SUPPLIER',
                'name'           => 'سند قبض تقسيط - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة تقسيط للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_INSTALLMENTS_OTHER',
                'name'           => 'سند قبض تقسيط - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة تقسيط للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_WALLET_CUSTOMER',
                'name'           => 'سند قبض محفظة إلكترونية - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة محفظة إلكترونية للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_WALLET_SUPPLIER',
                'name'           => 'سند قبض محفظة إلكترونية - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة محفظة إلكترونية للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_WALLET_OTHER',
                'name'           => 'سند قبض محفظة إلكترونية - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة محفظة إلكترونية للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_ONLINE_CUSTOMER',
                'name'           => 'سند قبض بنك أونلاين - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك أونلاين للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_ONLINE_SUPPLIER',
                'name'           => 'سند قبض بنك أونلاين - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك أونلاين للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_ONLINE_OTHER',
                'name'           => 'سند قبض بنك أونلاين - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك أونلاين للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_DIRECT_CUSTOMER',
                'name'           => 'سند قبض بنك مباشر - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك مباشر للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_DIRECT_SUPPLIER',
                'name'           => 'سند قبض بنك مباشر - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك مباشر للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_BANK_DIRECT_OTHER',
                'name'           => 'سند قبض بنك مباشر - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة بنك مباشر للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CHECK_CUSTOMER',
                'name'           => 'سند قبض شيك - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة شيك للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CHECK_SUPPLIER',
                'name'           => 'سند قبض شيك - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة شيك للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_RECEIPT_CHECK_OTHER',
                'name'           => 'سند قبض شيك - طرف آخر',
                'operation_type' => 'revenue',
                'priority'       => 20,
                'description'    => 'سند قبض بطريقة شيك للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CASH_CUSTOMER',
                'name'           => 'سند صرف نقدي - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة نقدي للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CASH_SUPPLIER',
                'name'           => 'سند صرف نقدي - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة نقدي للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CASH_OTHER',
                'name'           => 'سند صرف نقدي - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة نقدي للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CREDIT_CUSTOMER',
                'name'           => 'سند صرف بنكي - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنكي للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CREDIT_SUPPLIER',
                'name'           => 'سند صرف بنكي - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنكي للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CREDIT_OTHER',
                'name'           => 'سند صرف بنكي - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنكي للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_INSTALLMENTS_CUSTOMER',
                'name'           => 'سند صرف تقسيط - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة تقسيط للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_INSTALLMENTS_SUPPLIER',
                'name'           => 'سند صرف تقسيط - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة تقسيط للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_INSTALLMENTS_OTHER',
                'name'           => 'سند صرف تقسيط - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة تقسيط للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_WALLET_CUSTOMER',
                'name'           => 'سند صرف محفظة إلكترونية - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة محفظة إلكترونية للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_WALLET_SUPPLIER',
                'name'           => 'سند صرف محفظة إلكترونية - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة محفظة إلكترونية للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_WALLET_OTHER',
                'name'           => 'سند صرف محفظة إلكترونية - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة محفظة إلكترونية للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_ONLINE_CUSTOMER',
                'name'           => 'سند صرف بنك أونلاين - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك أونلاين للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_ONLINE_SUPPLIER',
                'name'           => 'سند صرف بنك أونلاين - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك أونلاين للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_ONLINE_OTHER',
                'name'           => 'سند صرف بنك أونلاين - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك أونلاين للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_DIRECT_CUSTOMER',
                'name'           => 'سند صرف بنك مباشر - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك مباشر للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_DIRECT_SUPPLIER',
                'name'           => 'سند صرف بنك مباشر - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك مباشر للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_BANK_DIRECT_OTHER',
                'name'           => 'سند صرف بنك مباشر - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة بنك مباشر للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CHECK_CUSTOMER',
                'name'           => 'سند صرف شيك - عميل',
                'operation_type' => 'customer_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة شيك للطرف: عميل',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CHECK_SUPPLIER',
                'name'           => 'سند صرف شيك - مورد',
                'operation_type' => 'supplier_payment',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة شيك للطرف: مورد',
                'is_active'      => 1,
            ],
            [
                'code'           => 'VOUCHER_PAYMENT_CHECK_OTHER',
                'name'           => 'سند صرف شيك - طرف آخر',
                'operation_type' => 'expense',
                'priority'       => 20,
                'description'    => 'سند صرف بطريقة شيك للطرف: طرف آخر',
                'is_active'      => 1,
            ],
            // ============================================================
            // الأرصدة الافتتاحية - الاحتفاظ بها فقط من التسويات القديمة
            // ============================================================
            [
                'code' => 'OPENING_BALANCE',
                'name' => 'أرصدة افتتاحية',
                'operation_type' => 'opening_balance',
                'priority' => 5,
                'description' => 'ترحيل أرصدة بداية السنة المالية',
                'is_active' => 1,
            ],
        ];

        foreach ($scenarios as $scenario) {
            PostingScenario::create($scenario);
        }

        $this->command->info(
            'PostingScenario seeded successfully! Total: ' . count($scenarios)
        );
    }
}
